Repository stanford-crfm/helm, pull requests merged in 2024-03, with the labels that each got.

#2237 Add OpenFlamingo
  requirements.txt
  setup.cfg
  src/helm/benchmark/model_metadata_registry.py
  src/helm/benchmark/presentation/run_specs_image2structure.conf
  src/helm/benchmark/run_expander.py
  src/helm/benchmark/run_spec_factory.py
  src/helm/clients/vision_language/open_flamingo/__init__.py
  src/helm/clients/vision_language/open_flamingo/src/__init__.py
  src/helm/clients/vision_language/open_flamingo/src/factory.py
  src/helm/clients/vision_language/open_flamingo/src/flamingo.py
  src/helm/clients/vision_language/open_flamingo/src/flamingo_lm.py
  src/helm/clients/vision_language/open_flamingo/src/helpers.py
  src/helm/clients/vision_language/open_flamingo/src/utils.py
  src/helm/clients/vision_language/open_flamingo_client.py
  src/helm/config/model_deployments.yaml
  src/helm/config/model_metadata.yaml
  src/helm/config/tokenizer_configs.yaml
Labels: models, VHELM

#2428 Support Alibaba Cloud's open-source VLMs: Qwen VL + Qwen VL Chat VLMs
  setup.cfg
  src/helm/benchmark/presentation/run_specs_vhelm_lite.conf
  src/helm/benchmark/run_spec_factory.py
  src/helm/benchmark/scenarios/vision_language/mmmu_scenario.py
  src/helm/benchmark/scenarios/vision_language/vqa_scenario.py
  src/helm/benchmark/static/schema_vlm.yaml
  src/helm/clients/vision_language/open_flamingo_client.py
  src/helm/clients/vision_language/qwen_vlm_client.py
  src/helm/config/model_deployments.yaml
  src/helm/config/model_metadata.yaml
  src/helm/config/tokenizer_configs.yaml
Labels: models, VHELM

#2443 LilyPond Annotator + Metric
  src/helm/benchmark/annotation/image2structure/lilypond_compiler_annotator.py
  src/helm/benchmark/metrics/vision_language/image_metrics.py
  src/helm/benchmark/run_specs/vlm_run_specs.py
Labels: metrics

#2472 Port Lilypond to i2s format
  src/helm/benchmark/annotation/image2structure/lilypond_compiler_annotator.py
  src/helm/benchmark/presentation/run_specs_image2structure.conf
  src/helm/benchmark/run_specs/vlm_run_specs.py
  src/helm/benchmark/scenarios/vision_language/image2structure/image2structure_scenario.py
  src/helm/benchmark/scenarios/vision_language/image2structure/musicsheet_scenario.py
  src/helm/benchmark/scenarios/vision_language/image2structure/sheetmusic2lilypond_scenario.py
  src/helm/benchmark/static/schema_vlm.yaml
Labels: VHELM

#2470 Add retry on image compilation
  src/helm/benchmark/annotation/image2structure/image_compiler_annotator.py
Labels: VHELM
